from typing import Dict, Any, Optional
from src.data.bybit_client import BybitClient

def find_actionable_trade(trade_setup: Dict[str, Any], symbol: str) -> Optional[Dict[str, Any]]:
    """
    Determines if a potential trade setup is currently actionable by checking the live market price.

    Args:
        trade_setup: A dictionary containing the parameters of a potential trade
                     (entry_zone, stop_loss, targets, etc.), generated by the trade_proposer.
        symbol: The symbol for the asset (e.g., 'BTCUSDT').

    Returns:
        The trade_setup dictionary if the current price is within the entry zone,
        making it an actionable trade. Otherwise, returns None.
    """
    if not trade_setup or 'entry_zone' not in trade_setup:
        return None

    client = BybitClient()
    current_price_str = client.get_market_price(symbol)

    if not current_price_str:
        print(f"WARNING: Could not retrieve current market price for {symbol}. Skipping trade check.")
        return None

    try:
        current_price = float(current_price_str)
    except (ValueError, TypeError):
        print(f"ERROR: Invalid price format received for {symbol}: {current_price_str}")
        return None

    entry_zone_top, entry_zone_bottom = trade_setup['entry_zone']
    trade_type = trade_setup.get('type')

    # Ensure top is actually higher than bottom for comparison
    upper_bound = max(entry_zone_top, entry_zone_bottom)
    lower_bound = min(entry_zone_top, entry_zone_bottom)

    # Check if the current price is within the entry zone
    if lower_bound <= current_price <= upper_bound:
        print(f"INFO: Actionable trade found for {symbol}! Price {current_price} is within entry zone ({lower_bound} - {upper_bound}).")

        # The trade setup is valid and the price is right. Return the actionable trade.
        # We can add a "status" field to make it explicit.
        trade_setup['status'] = 'ACTIONABLE'
        trade_setup['current_price'] = current_price
        return trade_setup
    else:
        # Price is not in the zone, so the trade is not actionable right now.
        # print(f"DEBUG: Price for {symbol} ({current_price}) is outside entry zone ({lower_bound} - {upper_bound}). No action.")
        return None

# The old functions are no longer needed with the new architecture.
# The background scanner will now call the proposer and then the finder.
def find_long_term_trades(scenario, historical_data) -> Optional[Dict[str, Any]]:
    # This function is deprecated and will be removed.
    # The new flow is cleaner.
    return None

def find_scalp_trades(scenario, historical_data) -> Optional[Dict[str, Any]]:
    # This function is deprecated and will be removed.
    return None
